# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 654ffbe7baac3908d223e9571ac4eb166a927ccb38d763f423dc9da477e66bf6f1f1996a2c493d39741f412d7d15d52c0d96fe564a5e5a1379973e5c5eb6ba55

test:
  secret_key_base: a2315ac997bf5b27f8faa991efa20af32c2622769435dd08ebd4562f6ecc920b78ccd6b18a9f6881e039425d97ae2fc676f0bb378291283cc9f8a14824751019

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
